name: Build all samples

on: push

jobs:
  findsamples:
    name: Discover samples to build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v4
    - id: set-matrix
      shell: python
      run: |
        import json, os
        matrix = json.dumps(os.listdir("samples"))
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f"matrix={matrix}", file=fh)

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: ["findsamples"]
    strategy:
      matrix:
        sample: ${{ fromJson(needs.findsamples.outputs.matrix) }}
        board: ["nucleo_f429zi"]

    steps:
    - uses: actions/checkout@v4
      with:
        path: colourful-kite
    - uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: colourful-kite
        toolchains: arm-zephyr-eabi
    - run: west build -b ${{ matrix.board }} colourful-kite/samples/${{ matrix.sample }}
